config/routes.rb
Rails.application.routes.draw do
  root 'pictures#index'

  # users
  resources :users , only: [:new,:create,:show]

  # sessions
  resources :sessions, only: [:new,:create,:destroy]

  # pictures
  resources :pictures do
    collection do
      post 'confirm'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :user
  mount_uploader :image, ImageUploader

  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :password, length: { minimum: 6 }
  before_validation { email.downcase! }

  has_secure_password

  has_many :pictures
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  before_action :login_required

  private

  def login_required
    redirect_to new_session_path unless current_user
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :picture_find,only: [:show,:destroy,:edit,:update]

  # 一覧表示
  def index
    @pictures = Picture.all
  end

  # 新規投稿
  def new
    @picture = Picture.new
  end

  def create
    @picture = current_user.pictures.build(picture_params)  
    if params[:back]
      render :new
    else
      if @picture.save
        flash[:danger] = "投稿しました"
        redirect_to pictures_path
      else
        flash.now[:danger] = "投稿できません"
        render :new
      end
    end
  end

  # 確認
  def confirm
    @picture = current_user.pictures.build(picture_params)
    render :new if @picture.invalid?
  end

  # 参照
  def show
  end

  # 編集
  def edit
    if current_user != @picture.user  
      redirect_to pictures_path
    end
  end

  def update
    if @picture.update(picture_params)
      flash[:danger] = "編集しました"
      redirect_to pictures_path
    else
      render :edit
    end
  end

  # 削除
  def destroy
    if current_user != @picture.user  
      redirect_to pictures_path
    else
      @picture.destroy
      flash[:danger] = "削除しました"
      redirect_to pictures_path
    end
  end

  private

  def picture_params
    params.require(:picture).permit(:content,:image,:image_cache)
  end

  def picture_find
    @picture = Picture.find(params[:id])
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new,:create]

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to pictures_path
    else
      flash.now[:danger] = "ログインに失敗しました"
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = "ログアウトしました"
    redirect_to new_session_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new,:create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error.html.erb
<% if name.errors.any? %>
  <div id="error_explanation ">
    <p class="alert alert-danger">エラー</p>
    <ul>
    <% name.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<header class="header">
<nav class="navbar navbar-light bg-light">
  <span class="navbar-brand mb-0 h1"><%= link_to "FacebookClone",pictures_path %></span>
  <ul class="nav justify-content-end">  
    <% if logged_in? %>
      <li class="nav-item">
        <%= link_to "新規投稿", new_picture_path,class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "プロフィール", user_path(current_user.id),class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "ログアウト", session_path(current_user.id), method: :delete,class:"nav-link" %>
      </li>
    <% else %>
      <li class="nav-item">
        <%= link_to "新規登録", new_user_path,class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "ログイン", new_session_path,class:"nav-link" %>
      </li>
    <% end %>
  </ul>
</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FacebookCloneApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="body">
    <%= render 'layouts/header' %>
    <div class="main">
      <% flash.each do |key,value| %>
        <%= content_tag(:div,value,class:"#{key}") %>
      <% end %>
     <%= yield %>
    </div>
  </body>
</html>

app/views/pictures/confirm.html.erb
<p class="title">以下の内容でよろしいですか？</p>
<%= form_with(model:@picture,local:true) do |form|  %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :image_cache %>

  <div>
  <%= @picture.content %>
  </div>
  
  <div>
  <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
  </div>
  
  <div class="confirm_btn">
  <%= form.submit "投稿",class:"btn btn-secondary btn-sm" %>
  <%= form.submit "戻る",name:"back",class:"btn btn-secondary btn-sm" %>
  </div>
<% end %>

app/views/pictures/edit.html.erb
<p class="title">編集</p>
<%= form_with(model:@picture,local:true,class:"new_edit_form") do |form|  %>

  <div>
    <%= form.text_area :content,class:"new_edit_content" %>
  </div>

  <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
    
  <div class="new_edit_image">
      <%= form.label :image,"画像を変更",class:"image_label"%><br>
      <%= form.file_field :image,class:"image_form" %>
      <%= form.hidden_field :image_cache %>
  </div>

  <div>
    <%= form.submit :編集,class:"btn btn-secondary btn-sm" %>
    <%= link_to "戻る",pictures_path,class:"btn btn-secondary btn-sm" %>
  </div>
<% end %>

app/views/pictures/index.html.erb
<% @pictures.reverse_each do |picture| %>
  <div class="picture">
    <div class="picture_user">
      <%= picture.user.name %>
      <%= link_to "詳細",picture_path(picture.id),class:'picture_detail btn btn-outline-secondary btn-sm' %>
      <% if current_user == picture.user %>
        <%= link_to "編集",edit_picture_path(picture.id),class:"picture_edit btn btn-outline-secondary btn-sm" %>
        <%= link_to "削除",picture_path(picture.id),method: :delete,class:"picture_delete btn btn-outline-secondary btn-sm" %>
      <% end %>
    </div>
    <div class="picture_content">
      <%= picture.content %>
    </div>
    <div class="picture_image">
      <%= image_tag picture.image.url %>
    </div>
  </div>
<% end %>

app/views/pictures/new.html.erb
<p class="title">投稿を作成</p>
<%= render 'layouts/error',name: @picture %>
<%= form_with(model:@picture,local:true,url:confirm_pictures_path,class:"new_edit_form") do |form|  %>

  <div>
    <%= form.text_area :content,class:"new_edit_content" %>
  </div>

  <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
    
  <div class="new_edit_image">
      <%= form.label :image,"画像を追加",class:"image_label"%><br>
      <%= form.file_field :image,class:"image_form" %>
      <%= form.hidden_field :image_cache %>
  </div>

  <div>
    <%= form.submit :確認,class:"btn btn-secondary btn-sm" %>
    <%= link_to "戻る",pictures_path,class:"btn btn-secondary btn-sm" %>
  </div>
<% end %>

app/views/pictures/show.html.erb
<p class="title">投稿詳細</p>
<div>
  <%= @picture.user.name %>
</div>
<%= l @picture.created_at %>
<div class="show_content">
  <%= @picture.content %>
</div>
<div class="show_image">
  <%= image_tag @picture.image.url %>
</div>
<%= link_to "戻る",pictures_path,class:"btn btn-secondary btn-sm" %>

app/views/users/new.html.erb
<p class="title">アカウント登録</p>
<%= render 'layouts/error',name: @user %>
<%= form_with(model: @user, local: true) do |form| %>  
  
  <div class="user_new_form">
    <%= form.text_field :name,placeholder:"名前" %> 
    <%= form.email_field :email,placeholder:"メールアドレス" %>
    <%= form.password_field :password,placeholder:"パスワード" %>
    <%= form.password_field :password_confirmation,placeholder:"パスワード確認" %>
  </div>
  
  <div class="user_new_btn">
    <%= form.submit "アカウント登録",class:"login_btn btn btn-primary" %>
  </div>
<% end %>

app/views/users/show.html.erb
<p class="title">プロフィール</p>
<p>ユーザー名: <%= current_user.name %></p>
<p>メールアドレス: <%= current_user.email %></p>